services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: onecompliance
    volumes:
      - ./create_roles.sql:/docker-entrypoint-initdb.d/create_roles.sql
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin-backup:/var/lib/pgadmin/storage/admin_example.com/shared
    user: "5050:5050"

volumes:
  pgdata:
  pgadmin-data:
